### ISSUE TITLE
Panic on unsafe type cast

### ISSUE THREAD

**Issue by dexhorthy** [replicatedhq/ship#579]
### Expected behavior

Ship can init a local directory via go-getter

### Actual behavior

Ship panics on a local directory (and likely in other places as well)

```
panic: interface conversion: state.State is state.VersionedState, not state.Empty

goroutine 1 [running]:
github.com/replicatedhq/ship/pkg/ship.(*Ship).Init(0xc00032ad80, 0x2b7f340, 0xc0009604c0, 0x0, 0x0)
        /Users/dex/go/src/github.com/replicatedhq/ship/pkg/ship/kustomize.go:52 +0x812
github.com/replicatedhq/ship/pkg/ship.(*Ship).InitAndMaybeExit(0xc00032ad80, 0x2b7f380, 0xc0000cc008, 0x0, 0xc0004c1c90)
        /Users/dex/go/src/github.com/replicatedhq/ship/pkg/ship/kustomize.go:20 +0x43
github.com/replicatedhq/ship/pkg/cli.Init.func1(0xc0004f7d40, 0xc0004c1ac0, 0x1, 0x1, 0x0, 0x0)
        /Users/dex/go/src/github.com/replicatedhq/ship/pkg/cli/init.go:40 +0x84
github.com/replicatedhq/ship/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004f7d40, 0xc0004c1a80, 0x1, 0x1, 0xc0004f7d40, 0xc0004c1a80)
        /Users/dex/go/src/github.com/replicatedhq/ship/vendor/github.com/spf13/cobra/command.go:698 +0x47a
github.com/replicatedhq/ship/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0004f7440, 0x1, 0x28c6c80, 0x1)
        /Users/dex/go/src/github.com/replicatedhq/ship/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/replicatedhq/ship/vendor/github.com/spf13/cobra.(*Command).Execute(0xc0004f7440, 0x1007580, 0xc0000b0058)
        /Users/dex/go/src/github.com/replicatedhq/ship/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/replicatedhq/ship/pkg/cli.Execute()
        /Users/dex/go/src/github.com/replicatedhq/ship/pkg/cli/root.go:84 +0x27
main.main()
        /Users/dex/go/src/github.com/replicatedhq/ship/cmd/ship/main.go:6 +0x20
```

### Information

- Ship version: bda5bb61
- Command line run:

```
ship init ./fixtures/terraform
```

### Steps to reproduce the behavior

```
bin/ship init ./fixtures/terraform
```

**Comment by dexhorthy** [comment]
Update -- this appears to occur with many init upstreams. Appears to have been introduced in 4ffd33d
